---
title: Learner, hopefully for life.
timezone: IST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
markdown: kramdown
rdiscount:
       extensions: [smart]
permalink: "/:title.html"
# permalink: /:categories/:title/
paginate: 5
port: 3000
safe: true
local: false  #Enable for github
# Use css from local directory.
# local: true

# edit here to achieve your personal greatness
url: https://sumit.murari.me
baseurl:
author: Sumit Murari
description: Place to keep my silly thoughts
avatar: profile.png
email: sumit@murari.me
email_feedback: true
github: murarisumit
# aboutme: murarisumit
linkedin: murarisumit
stackoverflow: 2735833
# stackoverflow_story: murarisumit
google_analytics: UA-64117471-1
feeds: true
plugins:
- jekyll-paginate

# needed for travis-ci build
exclude: [vendor]

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed
